import { DocumentVersionForChunking } from '../domain/chunking-types';

export function documentVersionFixture(
  overrides: Partial<DocumentVersionForChunking> = {},
): DocumentVersionForChunking {
  return {
    id: 'document-version-1',
    documentId: 'document-1',
    topicId: 'topic-1',
    frontierEntryId: 'frontier-entry-1',
    topicConfigurationVersion: 1,
    requestedUrl: 'https://example.com/laser-hair-removal',
    finalUrl: 'https://example.com/laser-hair-removal',
    canonicalUrl: 'https://example.com/laser-hair-removal',
    title: 'Laser Hair Removal',
    metaDescription: 'Laser hair removal guide',
    contentHash: 'abc123',
    extractorVersion: 'extractor-v1',
    cleanedMarkdown: [
      '# Laser Hair Removal',
      '',
      'Intro paragraph for the page with helpful context.',
      '',
      '## Prices',
      '',
      'Prices depend on the body area and number of sessions.',
      '',
      '## FAQ',
      '',
      '### Is laser hair removal painful?',
      '',
      'Most people describe the sensation as mild discomfort.',
    ].join('\n'),
    plainText: null,
    metadata: {
      headings: [
        { level: 1, text: 'Laser Hair Removal', position: 0 },
        { level: 2, text: 'Prices', position: 1 },
        { level: 2, text: 'FAQ', position: 2 },
        {
          level: 3,
          text: 'Is laser hair removal painful?',
          position: 3,
        },
      ],
      openGraph: {},
      twitterCard: {},
      wordCount: 42,
      characterCount: 260,
      contentType: 'text/html',
      cacheHeaders: {},
      robotsMeta: null,
      canonicalUrl: 'https://example.com/laser-hair-removal',
      hreflangLinks: {},
      publishedTime: null,
      updatedTime: null,
    },
    structuredData: [],
    languageHints: [{ tag: 'en', confidence: 0.9, source: 'html_lang' }],
    geoHints: [{ countryCode: 'PL', confidence: 0.6, source: 'url' }],
    createdAt: new Date('2026-07-07T00:00:00Z'),
    ...overrides,
  };
}
