import {
  LongTailCandidate,
  LongTailCombinationRule,
  LongTailDimension,
} from './domain/long-tail-discovery-types';
import {
  UNKNOWN_LONG_TAIL_METRICS,
  confidenceRank,
  lowestConfidence,
} from './long-tail-defaults';
import { stableLongTailKey } from './normalize-long-tail-text';

export class LongTailCandidateService {
  buildCandidates(options: {
    topicId: string;
    rule: LongTailCombinationRule;
    combinations: LongTailDimension[][];
    degraded: boolean;
  }): LongTailCandidate[] {
    return options.combinations.map((dimensions) => {
      const normalizedConcept = dimensions
        .map((dimension) => dimension.normalizedValue)
        .join(' ');
      const confidence = options.degraded
        ? 'medium'
        : lowestConfidence(dimensions.map((dimension) => dimension.confidence));
      const warnings = [
        ...missingMetricWarnings(),
        ...(options.degraded
          ? ['Degraded run lowered long-tail candidate confidence']
          : []),
      ];

      return {
        candidateKey: stableLongTailKey(options.rule.ruleKey, normalizedConcept),
        topicId: options.topicId,
        normalizedConcept,
        displayLabel: dimensions.map((dimension) => dimension.label).join(' '),
        dimensions,
        sourceSignals: dimensions.flatMap((dimension) => dimension.sourceSignals),
        evidenceSummary: `${dimensions.length} supported dimension(s) generated by ${options.rule.ruleKey}`,
        metrics: UNKNOWN_LONG_TAIL_METRICS,
        missingMetrics: ['searchVolume', 'keywordDifficulty', 'cpc', 'trafficPotential'],
        confidence,
        warnings,
        candidatePageTypeHint: options.rule.candidatePageTypeHint,
        status:
          confidenceRank(confidence) >= confidenceRank('medium')
            ? 'candidate'
            : 'needs_validation',
      };
    });
  }
}

function missingMetricWarnings(): string[] {
  return ['Provider-backed long-tail metrics are unavailable'];
}
